#!/usr/bin/env node
/**
 * Does the LIVE database still match the migration files?
 *
 * -- WHY THIS EXISTS ------------------------------------------------
 *
 * scripts/test-migrations.mjs replays every migration into an empty
 * Postgres and asserts the security properties, and CI runs it on every
 * push. Its own header is careful about what that proves:
 *
 *     "It does not claim production matches. Migrations here have been
 *      applied by hand in the SQL editor since at least 044, so this
 *      proves the FILES are correct, not that the live database agrees
 *      with them."
 *
 * That gap has no consequences right up until the day somebody builds a
 * new project from the files and copies the data across. Then a column
 * that exists in one and not the other is a failed import, at the worst
 * possible moment, with the old project already being decommissioned.
 *
 * This closes it. The replay's shape is recorded as a fingerprint per
 * table; the live database is asked for the same thing; anything that
 * disagrees is printed. NO OUTPUT IS THE GOOD ANSWER.
 *
 * -- WHY A FINGERPRINT AND NOT A DUMP ------------------------------
 *
 * Because the answer has to be READ. A schema dump of both sides and a
 * diff produces thousands of lines that differ in ways nobody cares about
 * - ownership, statistics targets, the order pg_dump felt like emitting
 * things in. One short hash per table over (column, type, nullable) is
 * the part that actually breaks a data copy, and the report is three
 * lines instead of three thousand.
 *
 * -- MODES ---------------------------------------------------------
 *
 *   --write   read PGURL (the scratch database test-migrations just
 *             built) and write scripts/schema-fingerprint.txt
 *   --check   read PGURL and fail if it disagrees with that file. This
 *             is what keeps the file from rotting: it runs in CI right
 *             after the replay, so a migration that changes a table and
 *             does not update the fingerprint fails the build.
 *   --sql     print a self-contained SQL block, with the committed
 *             fingerprints embedded, to run against PRODUCTION. It
 *             returns only the differences.
 *
 * The three modes exist so that the file is generated, verified and used
 * by the same code. A fingerprint file maintained by hand is a file that
 * is wrong by the second week.
 */

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FILE = join(root, 'scripts', 'schema-fingerprint.txt');

const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const DIM = '\x1b[2m';
const OFF = '\x1b[0m';

/** One row per base table in public and legal: name|hash|column count. */
const QUERY = `
select c.table_schema || '.' || c.table_name || '|'
       || left(md5(string_agg(c.column_name || ':' || c.data_type || ':' || c.is_nullable,
                              ',' order by c.column_name)), 8)
       || '|' || count(*)::text
  from information_schema.columns c
  join information_schema.tables t
    on t.table_schema = c.table_schema
   and t.table_name   = c.table_name
   and t.table_type   = 'BASE TABLE'
 where c.table_schema in ('public', 'legal')
 group by c.table_schema, c.table_name
 order by 1;
`;

function fingerprintFrom(url) {
  const res = spawnSync('psql', [url, '-qAt', '-v', 'ON_ERROR_STOP=1', '-c', QUERY], {
    encoding: 'utf8',
  });
  if (res.status !== 0) {
    console.error(res.stderr || 'psql failed');
    process.exit(1);
  }
  return res.stdout.split('\n').map((l) => l.trim()).filter(Boolean).sort();
}

const mode = process.argv[2] ?? '--check';
const url = process.env.PGURL || 'postgres://postgres@localhost:5432/aq_migration_test';

if (mode === '--sql') {
  if (!existsSync(FILE)) {
    console.error('No scripts/schema-fingerprint.txt. Run `npm run db:test` first.');
    process.exit(1);
  }
  const rows = readFileSync(FILE, 'utf8').split('\n').map((l) => l.trim()).filter(Boolean);
  const values = rows.map((r) => {
    const [tbl, cols, n] = r.split('|');
    return `    ('${tbl}', '${cols}', ${n})`;
  }).join(',\n');

  process.stdout.write(`-- Does the LIVE database still match the migration files?
--
-- Expected fingerprints below come from a real replay of every migration
-- in this repository. This returns ONLY what disagrees.
--
-- NO ROWS IS THE GOOD ANSWER.
--
-- Generated by: node scripts/schema-drift.mjs --sql

with expected(tbl, cols, n) as (values
${values}
),
live as (
  select c.table_schema || '.' || c.table_name as tbl,
         left(md5(string_agg(c.column_name || ':' || c.data_type || ':' || c.is_nullable,
                             ',' order by c.column_name)), 8) as cols,
         count(*)::int as n
    from information_schema.columns c
    join information_schema.tables t
      on t.table_schema = c.table_schema
     and t.table_name   = c.table_name
     and t.table_type   = 'BASE TABLE'
   where c.table_schema in ('public', 'legal')
   group by c.table_schema, c.table_name
)
select coalesce(e.tbl, l.tbl) as table_name,
       case
         when l.tbl is null then 'IN THE FILES, NOT IN LIVE'
         when e.tbl is null then 'IN LIVE, NOT IN THE FILES'
         else 'COLUMNS DIFFER'
       end as what,
       e.n as files_columns,
       l.n as live_columns
  from expected e
  full outer join live l on l.tbl = e.tbl
 where e.tbl is null
    or l.tbl is null
    or e.cols is distinct from l.cols
 order by 2, 1;
`);
  process.exit(0);
}

const now = fingerprintFrom(url);

if (mode === '--write') {
  writeFileSync(FILE, now.join('\n') + '\n');
  console.log(`${GREEN}  ok${OFF}  schema fingerprint written ${DIM}${now.length} tables${OFF}`);
  process.exit(0);
}

if (mode !== '--check') {
  console.error(`Unknown mode ${mode}. Use --write, --check or --sql.`);
  process.exit(1);
}

if (!existsSync(FILE)) {
  console.log(`${DIM}No scripts/schema-fingerprint.txt yet - writing it.${OFF}`);
  writeFileSync(FILE, now.join('\n') + '\n');
  process.exit(0);
}

const want = readFileSync(FILE, 'utf8').split('\n').map((l) => l.trim()).filter(Boolean).sort();
const wantMap = new Map(want.map((r) => [r.split('|')[0], r]));
const nowMap = new Map(now.map((r) => [r.split('|')[0], r]));

const added = now.filter((r) => !wantMap.has(r.split('|')[0]));
const gone = want.filter((r) => !nowMap.has(r.split('|')[0]));
const changed = now.filter((r) => {
  const k = r.split('|')[0];
  return wantMap.has(k) && wantMap.get(k) !== r;
});

if (!added.length && !gone.length && !changed.length) {
  console.log(`${GREEN}  ok${OFF}  schema fingerprint matches ${DIM}${now.length} tables${OFF}`);
  process.exit(0);
}

console.log(`${RED}FAIL${OFF}  the replayed schema no longer matches scripts/schema-fingerprint.txt`);
for (const r of gone) console.log(`        gone     ${r.split('|')[0]}`);
for (const r of added) console.log(`        new      ${r.split('|')[0]}`);
for (const r of changed) console.log(`        changed  ${r.split('|')[0]}`);
console.log(`\n${DIM}If a migration in this change was meant to do that, refresh the file:`
  + `\n  PGURL=<scratch db> node scripts/schema-drift.mjs --write`
  + `\nand commit it with the migration. The file is how the live database is`
  + `\nchecked before a move, so it is only useful while it is current.${OFF}`);
process.exit(1);
